# Generated by Django 6.0 on 2025-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
