# Generated by Django 6.0 on 2025-12-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_hub', '0002_executionlog_is_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mappingtemplate',
            unique_together={('source', 'target')},
        ),
    ]
