# Generated by Django 6.0 on 2025-12-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_hub', '0003_alter_mappingtemplate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mappingtemplate',
            unique_together=set(),
        ),
    ]
